# Generated by Django 4.2.2 on 2023-09-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwickedwhiskricelake.com%2Fproduct-category%2Fbakery%2Fcookies%2F&psig=AOvVaw1F7MYjrkXP7G88MCNwdSSR&ust=1694154529658000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCLiQlMnvl4EDFQAAAAAdAAAAABAF', max_length=500),
        ),
    ]
