# Generated by Django 4.2.2 on 2023-09-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.CharField(default='https://wickedwhiskricelake.com/wp-content/uploads/2023/04/EmptyDinnerPlates.jpg', max_length=500),
        ),
    ]
